{application,ex2,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[warmup]},
              {maintainers,[]},
              {licenses,[]},
              {links,[]}]}.
